app:
  build: ./app
#  volumes:
#    - /usr/src/app/
#  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
  links:
    - db:postgres
    - redis:redis
  env_file: ./app/.env
  ports:
    - "8000:8000"

web:
  build: ./web
  volumes_from:
    - app
  volumes:
    - /www/static
  links:
    - app:app
  restart: always
  ports:
    - "80:80"

db:
  restart: always
  build: ./db
  ports:
    - "5432:5432" 

redis:
  image: redis
  ports:
    - "6379:6379"
